### ISSUE TITLE
Missing Images: 10 in 115th Congress

### ISSUE THREAD

**Issue by frisch1** [unitedstates/images#160] opened 2018-07-30 23:54 UTC
We use these for machine learning vs. distribution. I know most are CC license via Wiki, but don't know the origin.

These are the 10. Thanks! 

https://factbase-congress-bioguide-photos.s3.amazonaws.com/C001115.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/E000298.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/G000584.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/G000585.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/H001078.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/H001079.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/J000299.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/L000587.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/L000588.jpg
https://factbase-congress-bioguide-photos.s3.amazonaws.com/N000190.jpg

**Comment by hugovk** [comment] 2018-07-31 05:32
I get access denied on those.

We can only add public domain images, not CC. Some Wikipedia images are allowed if they are official government photos or taken by the person's office. 

See also https://github.com/unitedstates/images/issues/125.

**Comment by hugovk** [comment] 2020-09-26 05:57
Closing as duplicate of #125.

**Closed as completed by hugovk** 2020-09-26 05:57 UTC
